### ISSUE TITLE
[Feature] .htaccess file for php

### ISSUE THREAD

**Issue by kolorafa** [Thulinma/MixedModeAuth#1]
Yea ! That's it, i wanted to do this myself :)

Installation in progress :)

You might add .htaccess file for Apache/other servers :)

**Comment by Thulinma** [comment]
Yeah, I use lighttpd myself, so I wrote that first... if I have time I'll add some configs for other servers.
You're also free to contribute config instructions/files yourself, of course!

**Comment by Thulinma** [comment]
.htaccess config is in the checkserver.php file of the latest release now.
