### ISSUE TITLE
Does this authenticate premium users too?

### ISSUE THREAD

**Issue by Rtzon** [Thulinma/MixedModeAuth#12]
I have a server, and I was wondering if it requires premium users to have a password too.

I don't want to make the premium users set a password, but I want the offline users to have to set a password.

Is that what this plugin does?

Thanks.

-Rtzon

**Comment by Thulinma** [comment]
Yes, that's exactly what this plugin was made for.

Note however, that even premium users will be asked to create a password - for use when/if the minecraft login servers are down. If MC login servers are up, they are not asked for their password at all and automatically logged in.
