### ISSUE TITLE
Not loading with Multicraft?

### ISSUE THREAD

**Issue by cooljonny1** [Thulinma/MixedModeAuth#13]
Well I just recently got my server dedicated and started using the panel of Multicraft. All my other plugins work fine but essentials is not working at all. I can't find anywhere on the console about any error but I'm pretty sure it loaded, just not working.
If you are in-game , and you try to do /time or /weather, it does NOT say "Unknown command" but it doesn't do anything.
Even /essentials doesn't work. 
Any ideas?
BTW: This is the most recent build of essentials. I also tried it with 1 earlier build and it won't work.

**Comment by Thulinma** [comment]
This is for tracking MixedModeAuth issues - I'm not the author of Essentials.
