### ISSUE TITLE
When do you plan to have 1.1 RB?

### ISSUE THREAD

**Issue by djhopper01** [Thulinma/MixedModeAuth#14]
I'd be fine adding the server mod to the 1.1 RB. If you can provide a patch file or whatever you think I would need, I can do it myself. Thanks a lot for the great work on this mod.

**Comment by Thulinma** [comment]
Simply clone https://github.com/Thulinma/CraftBukkit/tree/preloginoverride and rebase it on whichever CraftBukkit build from their official git and it should work.

I'll provide a download for a 1.1 RB version myself shortly, as well.

**Comment by djhopper01** [comment]
Awesome, thank you.
