### ISSUE TITLE
Plugins with tekkit? HELP!

### ISSUE THREAD

**Issue by lassu** [Thulinma/MixedModeAuth#23]
I would like to add this plugin to my tekkit server, but the game just simply doesn't use custom plugins. When i type "plugins" so i can see the list it's not in there. I can't use the commands for this plugin. I haven't installed ANY other plugin yet, please help.

**Comment by Thulinma** [comment]
The server mod required for MixedModeAuth to work properly is not part of tekkit, and since tekkit itself is not open source (though all the parts are...) it is quite hard to add this. You can however still use the plugin in legacy mode and I've done so myself in the past without problems. Are you sure you installed it in the correct (plugin) folder? It shouldn't be with the other server mods, but in the folder for plugins.

**Comment by lassu** [comment]
Thanks, i guess i'll try.

**Comment by lassu** [comment]
I was trying and surfing google today but i just don't know how to "put an entry in the hosts file" or make files writeable to the web. So I can't even install the php script... Is there an easier way if I run the server in offline mode? Sorry for wasting your time but I really don't know how to do this...

**Comment by Thulinma** [comment]
Unfortunately if you cannot install the server mod (which makes this all very easy) the hard way is the only way that can work. Assuming you are running Windows, a search for "hosts file windows" should get you the information you need. As for the PHP script - you'll need a running webserver with PHP support for that, and there are several options for that (apache+php is most common, and has most help available online - I prefer nginx+php-fcgi myself).

I don't really have enough free time to walk you through all this, but if you search/ask around you should be able to get it all set up. :-)

**Comment by lassu** [comment]
uhm... Im not quite sure what i did, because my server is still runing only in offline mode but after searching the wikipedia for hours I think i did it! The plugin is working on the server, thank you for your help! Farewell!

**Comment by Thulinma** [comment]
No problem - good to hear you got it working. :-)
