### ISSUE TITLE
Client Mod

### ISSUE THREAD

**Issue by 1moosey1** [Thulinma/MixedModeAuth#8]
Excuse me good sir your client mod to get offline people on a online server with mixed mode auth seems to not be working i'd greatly appreciate it if you could update it :) Thanks.

**Comment by JohnPulse** [comment]
I also have this issue.

The wt.class file won't do anything on MC1.0. Could you please take a look at this?
Thank you again for your time.

Regards,
John

**Comment by Thulinma** [comment]
Yes, I'm aware the mod only works on 1.8/1.9. I'll make a file for 1.0.0 as soon as I have the time to do so.

**Comment by 1moosey1** [comment]
Whenever you finish let me know i'll donate some money I greatly appreciate your work! :)

**Comment by Thulinma** [comment]
Here is the updated client mod for 1.0.0/1.0.1:

https://github.com/downloads/Thulinma/MixedModeAuth/abp.class
