### ISSUE TITLE
Issues with the new abp.class

### ISSUE THREAD

**Issue by JohnPulse** [Thulinma/MixedModeAuth#9]
Hi there!

I'm having some problems using the new client mod.
When connecting to a server with MixedmodeAuth installed (my own, non-legacy mode), I have the following error on the client.

Failed to connect to the server

java.lang.SecurityExeption: SHA-256 digest error for abp.class

Any help to bypass this error will be appreciated :)

Best regards,
JohnPulse

**Comment by Thulinma** [comment]
You need to delete the META-INF folder from the .jar file to prevent errors like that one.
